### ISSUE TITLE
Commenting your code

### ISSUE THREAD

**Issue by zannain** [mistytree/teacozy#1]
Get into the habit of commenting your code, you will thank yourself later when you return to code that you wrote some time ago. I noticed that you organized your code by giving them class names describing their position. Since the position is only important to you or anyone working with you on your web page, adding comments regarding the position of what a selection of code is doing makes more sense opposed to giving an element a class name describing the relative position. This will help anyone reading your code know exactly what a portion of your code is doing, it will help you bring yourself up to speed when you return to some web page that you wrote some time ago as opposed to working your way down from the top. Lastly be descriptive with your comments! Name your classes based on the function they serve not their position. 

```css
/* Styles applied here are for navigation */
nav {  
    display: flex;
}  

/* Styles for article*/ 
section {  
    background: #000; } 

/* Styles for Footer*/ 

footer {  
margin:10px; 
}
```
